// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('number plus blank space', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('number plus blank space', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 942, height: 1020 })
    await driver.findElement(By.css(".input-group:nth-child(2) > label")).click()
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("1")
    await driver.findElement(By.css(".wrapper")).click()
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys(" ")
    await driver.findElement(By.css("button:nth-child(1)")).click()
  })
})
