// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('7-8', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('7-8', async function() {
    await driver.get("http://localhost:8000/src/src/")
    await driver.manage().window().setRect({ width: 1050, height: 1002 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("7")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("8")
    await driver.findElement(By.css("button:nth-child(2)")).click()
    await driver.findElement(By.css("button:nth-child(3)")).click()
    await driver.close()
  })
})
